// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaHorarios.Infrastructure;

#nullable disable

namespace SistemaHorarios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaHorarios.Domain.Asignatura", b =>
                {
                    b.Property<int>("IdAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignatura"));

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAsignatura");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Aula", b =>
                {
                    b.Property<int>("IdAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAula"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAula");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorasMaximas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDocente");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("NivelEducativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdGrupo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int");

                    b.Property<int>("IdAula")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdAula");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Horario", b =>
                {
                    b.HasOne("SistemaHorarios.Domain.Asignatura", "Asignatura")
                        .WithMany("Horarios")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Domain.Aula", "Aula")
                        .WithMany("Horarios")
                        .HasForeignKey("IdAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Domain.Docente", "Docente")
                        .WithMany("Horarios")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Domain.Grupo", "Grupo")
                        .WithMany("Horarios")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Aula");

                    b.Navigation("Docente");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Asignatura", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Aula", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Docente", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaHorarios.Domain.Grupo", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
